
import { getServerSession } from 'next-auth';
import Wrapper from './sessionWrapper'
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async  function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body>
           <Wrapper session={session}>
             {children}
           </Wrapper>
      </body>
    </html>
  );
}
